name: Build and Deploy
on:
  push:
    tags: ["*"]
    branches: ["master"]

permissions:
  contents: read

jobs:
  docker-build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: EthDevOps/workflows/.github/workflows/basic-docker-build-openbao.yaml@main
    with:
      bao_role: protocol-security-website-ci
      bao_secret_path: secret/protocol-security/data/website/production/docker
